notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

language: ruby

services:
  - docker

script:
  - set -e
  - echo 'Build and check docker image'
  - docker build -t battenberg .
  - docker images | grep -c battenberg
  - echo 'Verify program(s) from each inherited base image - dockstore-cgpbigwig'
  - docker run -t --rm battenberg bwjoin --version
  - echo 'Verify program(s) from each inherited base image - dockstore-cgpmap'
  - docker run -t --rm battenberg bwa_mem.pl -version
  - docker run -t --rm battenberg bammarkduplicates2 --version
  - docker run -t --rm battenberg samtools --version
  - docker run -t --rm battenberg bash -c 'bwa 2>&1 | grep Version'
  - echo 'Verify program(s) from this repo'
  - docker run -t --rm battenberg Rscript -e 'library(ASCAT)'
  - docker run -t --rm battenberg Rscript -e 'library(Battenberg)'
  - docker run -t --rm battenberg battenberg.pl -v
  - docker run -t --rm battenberg battenberg_version.pl
  - docker run -t --rm battenberg battenberg_CN_to_VCF.pl -v
  - docker run -t --rm battenberg bb_vcf_to_ascat_cn.pl
  - docker run -t --rm battenberg download_generate_bberg_ref_files.pl -v

